---
- name: Configure VueServer
  hosts: vue
  become: yes

  tasks:
  - name: Update yum rep
    shell: yum -y update
  
  - name: Install Nginx
    shell: 
           amazon-linux-extras install -y nginx1
           service nginx start
           chkconfig nginx on

  - name: Install NodeJS
    shell: 
          curl -sL https://rpm.nodesource.com/setup_14.x | sudo bash -
          yum install -y nodejs
  
  - name: Install Yarn
    shell:
          curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo
          yum install -y yarn
  
  - name: Install Git & download site files
    shell:
          yum install -y git
          git clone https://github.com/vuejs/vue.git
  
  - name: Yarn build
    shell:
          yarn
          yarn build
          

  - name: Reload Nginx
    shell: nginx -s reload
